Refatorar outros endpoints de treino no codex neodv 1617 (#75)
* - adds ModelTypes enum for async and sync model types
- implements __str__ method in ModelTypes for string representation

* - adds validate_dataset function to check dataset type and hash format
- raises TypeError for invalid dataset types
- raises ValueError for invalid dataset hash prefixes

* - refactors python_version assignment to use validate_python_version return value
- removes redundant string manipulation in multiple locations

* - refactors python_version assignment to use validate_python_version return value
- removes redundant string manipulation in multiple locations

* - creates `__init__.py` in `src/mlops_codex/training/` to expose `MLOpsTrainingExperiment`, `MLOpsTrainingClient`, and `MLOpsTrainingLogger`

* - introduces a base class `ITrainingExecution` with abstract methods for training execution logic, status checks, file uploads, and model promotion in MLOps context
- integrates file upload and execution registration functionality
- handles authentication, training state management, and model promotion with dynamic method calls for different actions in the training pipeline

* - remove training execution class
- migrate functions to v2
- simplifies code
- refactor derivative classes

* - adds CustomTrainingExecution class with validation and file upload logic
- adds AutoMLTrainingExecution class for automl training execution with validation and file upload
- introduces validate method in CustomTrainingExecution and AutoMLTrainingExecution
- adds __upload_script_file method for script file upload in CustomTrainingExecution
- adds __upload_conf_dict method for configuration dictionary upload in AutoMLTrainingExecution
- raises InputError if required parameters are missing in CustomTrainingExecution and AutoMLTrainingExecution
- integrates file extension validation for source, requirements, and config files

* - file to handle specific validations for training

* - improve initialization
- remove from repl login, password, url and mlops base class

* - improve print

* - add constants.py

* - fix unused-import (F401)

* - ruff

* - adds model_type as a frozen field in TrainingConfig
- removes redundant assignment of model_type from API response

* - adds model_type to training execution payload for CustomTrainingExecution and AutoMLTrainingExecution

* - refactors validate method to be a class method in CustomTrainingExecution
- modifies validate method to check specific required fields using class keys
- adds constructor to CustomTrainingExecution for initialization and file uploads

* - fix AttributeError: 'CustomTrainingExecution' object has no attribute 'base_url'

* - fix: give a default description if it is missing

* - fix: KeyError: 'train_reference'

* - fix: 'train_reference' is missing
- move python validation to __init__

* - fix: 'extra_files' key is missing

* - fix: use v2 url

* - fix: use v2 url

* - fix: RecursionError: maximum recursion depth exceeded in comparison

* - fix: lightgbm 3.3.2 vulnerability PYSEC-2024-231 4.6.0

* - modifies logging format to split dataset hash info into a separate line

* - adds logger info for validation step in CustomTrainingExecution
- refactors AutoMLTrainingExecution validation method to return data dictionary
- moves initialization logic from validate method to __init__ in AutoMLTrainingExecution

* - fix: "wait_complete" key missing

* - fix: get correct keys
- fix: condition was true
- fix: correct url

* - create new notebook to v2 example

* - add docstrings

* - add small description